name: Generate Pacman Graph

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Pacman Contribution Graph
        uses: Platane/snk@v3
        with:
          github_user_name: furkanmturgut
          outputs: |
            output/pacman-contribution-graph.svg
            output/pacman-contribution-graph-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
